// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ8DD4jMDbFpLNDS9dh62aFZvzYyKxtos',
    appId: '1:840879353544:web:58abae3f750ea0880a3ffd',
    messagingSenderId: '840879353544',
    projectId: 'sunrise-service-centre',
    authDomain: 'sunrise-service-centre.firebaseapp.com',
    storageBucket: 'sunrise-service-centre.appspot.com',
    measurementId: 'G-1490XF8B24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEa5SX0LDCPGeTBATIYDhHUjMBOtVr-w',
    appId: '1:840879353544:android:174195dc6701c6310a3ffd',
    messagingSenderId: '840879353544',
    projectId: 'sunrise-service-centre',
    storageBucket: 'sunrise-service-centre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ZuSzLu83qUOAKwOAgAVML4N8PyDdTdI',
    appId: '1:840879353544:ios:444271f695ea61f20a3ffd',
    messagingSenderId: '840879353544',
    projectId: 'sunrise-service-centre',
    storageBucket: 'sunrise-service-centre.appspot.com',
    iosBundleId: 'com.example.ssc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ZuSzLu83qUOAKwOAgAVML4N8PyDdTdI',
    appId: '1:840879353544:ios:444271f695ea61f20a3ffd',
    messagingSenderId: '840879353544',
    projectId: 'sunrise-service-centre',
    storageBucket: 'sunrise-service-centre.appspot.com',
    iosBundleId: 'com.example.ssc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ8DD4jMDbFpLNDS9dh62aFZvzYyKxtos',
    appId: '1:840879353544:web:3e2d77754f993da80a3ffd',
    messagingSenderId: '840879353544',
    projectId: 'sunrise-service-centre',
    authDomain: 'sunrise-service-centre.firebaseapp.com',
    storageBucket: 'sunrise-service-centre.appspot.com',
    measurementId: 'G-LHFBQFS30J',
  );
}
